margin = 200
always_for_in = "nothing"
whitespace_typedefs = false
whitespace_in_kwargs = true
join_lines_based_on_source = true
align_matrix = true
align_pair_arrows = true 
align_conditional = true 
align_assignment = true 
format_docstrings = true
format_markdown = true