[files]
extend-exclude = ["*.svg", "*.toml"]

[default.extend-words]
ue = "ue"
ba = "ba"
nd = "nd"
Numer = "Numer"
Secrest = "Secrest"

[type.qrtables]
extend-glob = ["**/gaussquad_*_table.jl"]

[type.qrtables.extend-words]
Methode = "Methode"

[type.feintro]
extend-glob = ["**/fe_intro.md"]

[type.feintro.extend-words]
Strang = "Strang"
