# Family descriptions and representative examples.
# All built-in shape values are evaluated by Ferrite, never reimplemented here.

const CATALOG = [
    (
        slug = "lagrange", title = "Lagrange", ip = Lagrange{RefTriangle, 2}(),
        kind = :point, continuity = "H¹ · continuous values", space = raw"\mathcal P_2 = \operatorname{span}\{1,x,y,x^2,xy,y^2\}",
        summary = "Values at vertices and edge midpoints define a quadratic field.",
        detail = "The six nodal basis functions are one at their own node and zero at every other node. Edge nodes are shared between adjacent cells, making the assembled field continuous. Negative lobes in a quadratic vertex basis are expected.",
        functional = raw"\ell_i(u)=u(\boldsymbol x_i)",
        note = "This page shows the quadratic triangle. Ferrite also provides line, quadrilateral, tetrahedral, hexahedral, prism, and pyramid variants; see the interpolation API for supported orders.",
        defelement = "lagrange",
    ),
    (
        slug = "discontinuous-lagrange", title = "Discontinuous Lagrange", ip = DiscontinuousLagrange{RefTriangle, 1}(),
        kind = :point, continuity = "L² · cell-local values", space = raw"\mathcal P_1 = \operatorname{span}\{1,x,y\}",
        summary = "The same local nodal shapes, with independent dofs in each cell.",
        detail = "The linear basis is identical to the continuous Lagrange basis on a single triangle. The difference is in assembly: dofs belong to the cell and are not shared. The sampling locations still lie at the vertices; a dof's location and its topological ownership are different concepts.",
        functional = raw"\ell_i(u)=u(\boldsymbol x_i)",
        note = "A single-cell plot cannot show a discontinuity between cells. This example deliberately retains Ferrite's actual vertex sampling locations instead of moving them into the interior.",
        defelement = "discontinuous-lagrange",
    ),
    (
        slug = "bubble-enriched-lagrange", title = "Bubble-enriched Lagrange", ip = BubbleEnrichedLagrange{RefTriangle, 1}(),
        kind = :point, continuity = "H¹ · continuous values", space = raw"\mathcal P_1 \oplus \operatorname{span}\{xy(1-x-y)\}",
        summary = "Three vertex values and a cell bubble add an interior mode.",
        detail = "Ferrite uses a nodal basis at the three vertices and the barycentre. The interior basis is 27xy(1−x−y), and vanishes on every edge. The vertex bases are corrected by the bubble so that they vanish at the barycentre too.",
        functional = raw"\ell_i(u)=u(\boldsymbol x_i),\qquad \boldsymbol x_4=(1/3,1/3)",
        note = "The constructor's order is 1, but the bubble has total polynomial degree 3. An interior location does not imply an integral functional: this element uses PointValue for all four dofs.",
        defelement = "bubble-enriched-lagrange",
    ),
    (
        slug = "serendipity", title = "Serendipity", ip = Serendipity{RefQuadrilateral, 2}(),
        kind = :point, continuity = "H¹ · continuous values", space = raw"\mathcal S_2=\operatorname{span}\{1,x,y,x^2,xy,y^2,x^2y,xy^2\}",
        summary = "Quadratic edge traces with eight nodes and no centre dof.",
        detail = "Four vertex values and four edge-midpoint values determine this quadrilateral element. Its space omits the x²y² term of the nine-node tensor-product Q₂ element. The surface view makes the negative interior values of vertex basis functions visible.",
        functional = raw"\ell_i(u)=u(\boldsymbol x_i)",
        note = "The reference square is [−1,1]². Ferrite also implements the quadratic serendipity hexahedron.",
        defelement = "serendipity",
    ),
    (
        slug = "crouzeix-raviart", title = "Crouzeix–Raviart", ip = CrouzeixRaviart{RefTriangle, 1}(),
        kind = :point, continuity = "Nonconforming · shared midpoint values", space = raw"\mathcal P_1=\operatorname{span}\{1,x,y\}",
        summary = "Linear fields joined through edge-midpoint values.",
        detail = "Ferrite's functionals are point evaluations at edge midpoints. Adjacent cells agree there, but their traces can differ elsewhere along the edge. For a linear trace, its midpoint value equals its edge average; this equivalence does not hold for an arbitrary function being interpolated.",
        functional = raw"\ell_i(u)=u(\boldsymbol m_i)",
        note = "The dof_functionals API reports PointValue at each edge midpoint, rather than an integral moment.",
        defelement = "crouzeix-raviart",
    ),
    (
        slug = "rannacher-turek", title = "Rannacher–Turek", ip = RannacherTurek{RefQuadrilateral, 1}(),
        kind = :point, continuity = "Nonconforming · shared midpoint values", space = raw"\operatorname{span}\{1,x,y,x^2-y^2\}",
        summary = "A rotated quadratic space determined at four edge midpoints.",
        detail = "This is Ferrite's point-value variant on the reference square. Its saddle-shaped modes come from x²−y². Matching edge-midpoint values does not make the full trace continuous, and midpoint evaluation is not interchangeable with an edge average in this space.",
        functional = raw"\ell_i(u)=u(\boldsymbol m_i)",
        note = "The constructor's order 1 is a family parameter: the local space includes a quadratic term. Ferrite also implements a hexahedral variant.",
        defelement = "crouzeix-raviart",
    ),
    (
        slug = "raviart-thomas", title = "Raviart–Thomas", ip = RaviartThomas{RefTriangle, 1}(),
        kind = :normal, continuity = "H(div) · continuous normal trace", space = raw"[\mathcal P_0]^2 \oplus \operatorname{span}\{(x,y)^{\mathsf T}\}",
        summary = "One outward flux integral per edge determines a vector field.",
        detail = "The arrows show the vector basis, while the edge plot shows the signed normal trace, including the edge-length factor. The active edge carries unit total flux and the other two carry zero flux. Interior vector samples are not interpolation nodes.",
        functional = raw"\ell_e(\boldsymbol v)=\int_e \boldsymbol v\cdot\boldsymbol n_e\,\mathrm ds",
        note = "Ferrite's order 1 is the lowest-order RT element (polynomial subdegree 0 in DefElement). Normal directions here are outward on the reference triangle. Physical-cell orientation is handled by Ferrite.",
        defelement = "raviart-thomas",
    ),
    (
        slug = "brezzi-douglas-marini", title = "Brezzi–Douglas–Marini", ip = BrezziDouglasMarini{RefTriangle, 1}(),
        kind = :normal, continuity = "H(div) · continuous normal trace", space = raw"[\mathcal P_1]^2",
        summary = "Two weighted flux moments per edge determine a linear vector field.",
        detail = "Each edge has two moments, weighted by 1−s and s along the oriented edge. The numbered arrows locate the owning edge and indicate its normal; they are not point evaluations. The trace plot displays the weighted density for the selected functional, whose signed area is one.",
        functional = raw"\ell_{e,r}(\boldsymbol v)=\int_0^1 \boldsymbol v(\boldsymbol\gamma_e(s))\cdot\boldsymbol n_e\,q_r(s)\,|\boldsymbol\gamma'_e(s)|\,\mathrm ds,\quad (q_1,q_2)=(1-s,s)",
        note = "The weights follow the reference-edge directions (vertex 1→2, 2→3, 3→1). NormalMoment identifies the functional kind, but does not encode its weight or normalization; these are specified explicitly in this example.",
        defelement = "brezzi-douglas-marini",
    ),
    (
        slug = "nedelec", title = "Nédélec · first kind", ip = Nedelec{RefTriangle, 1}(),
        kind = :tangent, continuity = "H(curl) · continuous tangential trace", space = raw"[\mathcal P_0]^2 \oplus \operatorname{span}\{(-y,x)^{\mathsf T}\}",
        summary = "One oriented circulation integral per edge determines a vector field.",
        detail = "The field is drawn with arrows, and the selected edge is marked in its tangential direction. The trace plot shows circulation density, not vector magnitude. Only the selected edge has a unit circulation integral.",
        functional = raw"\ell_e(\boldsymbol v)=\int_e \boldsymbol v\cdot\boldsymbol t_e\,\mathrm ds",
        note = "Ferrite's order 1 is the lowest-order first-kind Nédélec element (polynomial subdegree 0 in DefElement). Tangents follow vertex 1→2, 2→3, 3→1. Covariant Piola mapping preserves these circulation integrals.",
        defelement = "nedelec1",
    ),
]
