# Download some assets necessary for docs/testing not stored in the repo
import Downloads
import Scratch

# Example screenshots (static PNG images) and animations (GIFs) are generated by
# docs/generate_screenshots.jl and stored on the gh-pages branch. Each comes as
# a light/dark pair that custom.css switches between per Documenter theme.
# For local previews, docs/generate_screenshots.jl leaves freshly rendered
# assets in docs/screenshot-assets/; use those instead of downloading so you
# can preview without first uploading them to gh-pages.
const local_assets = joinpath(@__DIR__, "screenshot-assets")

# Downloaded assets are kept in a scratch space in the depot so that they don't
# have to be re-downloaded for every build (in CI the scratch space is preserved
# between runs by julia-actions/cache). Cached copies are revalidated with a
# HEAD request, but used as-is if GitHub can't be reached (rate limits etc.).
# Run `using Scratch; delete_scratch!(Ferrite, "downloaded_assets")` to force
# fresh downloads.
const asset_cache = Scratch.get_scratch!(Ferrite, "downloaded_assets")

# Set to false on the first failed server check to skip validation of the
# remaining files (the server is likely unreachable for those too).
const asset_server_reachable = Ref(true)

function find_header(headers, name)
    idx = findfirst(kv -> lowercase(kv.first) == name, headers)
    return idx === nothing ? nothing : headers[idx].second
end

# ETag of the asset on the server, or nothing if it can't be determined. Note
# that the ETag depends on the content encoding so only ETags from these HEAD
# requests are compared with each other.
function remote_etag(url)
    resp = Downloads.request(url; method = "HEAD", throw = false)
    resp isa Downloads.Response && resp.status == 200 || return nothing
    return find_header(resp.headers, "etag")
end

function download_asset(url, path)
    local resp
    for sleeptime in (0, 1, 5) # retry transient failures
        sleep(sleeptime)
        resp = open(path, "w") do io
            Downloads.request(url; output = io, throw = false)
        end
        resp isa Downloads.Response && resp.status == 200 && return
    end
    error("failed to download $url: $(sprint(show, resp))")
end

# Return the path to the asset in the cache, downloading it if it is missing
# from the cache or outdated compared to the server.
function cached_asset(file)
    cfile = joinpath(asset_cache, file)
    etagfile = cfile * ".etag"
    url = Ferrite.asset_url(file)
    etag = asset_server_reachable[] ? remote_etag(url) : nothing
    if etag === nothing && asset_server_reachable[]
        asset_server_reachable[] = false
        isfile(cfile) && @warn "Could not fetch the current ETag for cached assets; using the cached copies without checking that they are up to date." url
    end
    if isfile(cfile) && (etag === nothing || (isfile(etagfile) && read(etagfile, String) == etag))
        return cfile
    end
    tmp = tempname(asset_cache)
    download_asset(url, tmp)
    mv(tmp, cfile; force = true)
    etag === nothing ? rm(etagfile; force = true) : write(etagfile, etag)
    return cfile
end

variants(names, ext) = [n * v * ext for n in names for v in ("-light", "-dark")]

function fetch_assets(dir, files)
    mkpath(dir)
    for file in files
        afile = joinpath(dir, file)
        isfile(afile) && continue
        localsrc = joinpath(local_assets, file)
        if isfile(localsrc)
            cp(localsrc, afile)
        else
            cp(cached_asset(file), afile)
        end
    end
    return
end

# Tutorials
fetch_assets(
    joinpath(@__DIR__, "src", "tutorials"),
    vcat(
        variants(
            [
                "heat_equation", "linear_elasticity", "incompressible_elasticity",
                "incompressible_elasticity_pressure",
                "hyperelasticity", "plasticity", "computational_homogenization",
                "stokes-flow", "dg_heat_equation", "linear_shell",
                "linear_elasticity_stress", "elastodynamics_modes", "darcy_flow",
            ], ".png"
        ),
        variants(["transient_heat", "elastodynamics", "porous_media", "ns_vs_diffeq", "reactive_surface", "heat_adaptivity"], ".webp"),
    ),
)

# How-to guides
fetch_assets(
    joinpath(@__DIR__, "src", "howto"),
    variants(["postprocessing", "postprocessing_cutline", "coloring"], ".png"),
)

# Code gallery
fetch_assets(
    joinpath(@__DIR__, "src", "gallery"),
    vcat(
        variants(["helmholtz", "landau_orig", "landau_opt", "topology_optimization_result"], ".png"),
        variants(["quasi_incompressible_hyperelasticity", "topology_optimization", "elasticity_adaptivity"], ".webp"),
    ),
)
