# Download some assets necessary for docs/testing not stored in the repo
import Downloads

# Example screenshots (static PNG images) and animations (GIFs) are generated by
# docs/generate_screenshots.jl and stored on the gh-pages branch. Each comes as
# a light/dark pair that custom.css switches between per Documenter theme.
# For local previews, docs/generate_screenshots.jl leaves freshly rendered
# assets in docs/screenshot-assets/; use those instead of downloading so you
# can preview without first uploading them to gh-pages.
const local_assets = joinpath(@__DIR__, "screenshot-assets")

variants(names, ext) = [n * v * ext for n in names for v in ("-light", "-dark")]

function fetch_assets(dir, files)
    mkpath(dir)
    for file in files
        afile = joinpath(dir, file)
        isfile(afile) && continue
        localsrc = joinpath(local_assets, file)
        if isfile(localsrc)
            cp(localsrc, afile)
        else
            Downloads.download(Ferrite.asset_url(file), afile)
        end
    end
    return
end

# Tutorials
fetch_assets(
    joinpath(@__DIR__, "src", "tutorials"),
    vcat(
        variants(
            [
                "heat_equation", "linear_elasticity", "incompressible_elasticity",
                "incompressible_elasticity_pressure",
                "hyperelasticity", "plasticity", "computational_homogenization",
                "stokes-flow", "dg_heat_equation", "linear_shell",
                "linear_elasticity_stress", "elastodynamics_modes", "darcy_flow",
                "magnetostatics",
            ], ".png"
        ),
        variants(["transient_heat", "elastodynamics", "porous_media", "ns_vs_diffeq", "reactive_surface", "heat_adaptivity"], ".webp"),
    ),
)

# How-to guides
fetch_assets(
    joinpath(@__DIR__, "src", "howto"),
    variants(["postprocessing", "postprocessing_cutline", "coloring"], ".png"),
)

# Code gallery
fetch_assets(
    joinpath(@__DIR__, "src", "gallery"),
    vcat(
        variants(["helmholtz", "landau_orig", "landau_opt", "topology_optimization_result"], ".png"),
        variants(["quasi_incompressible_hyperelasticity", "topology_optimization", "elasticity_adaptivity"], ".webp"),
    ),
)
