Base.@deprecate_binding DirichletBoundaryConditions ConstraintHandler
Base.@deprecate_binding DirichletBoundaryCondition Dirichlet
@deprecate end_assemble finish_assemble
Base.@deprecate_binding Assembler IJVAssembler
