export
# Interpolations
    Interpolation,
    RefCube,
    RefTetrahedron,
    BubbleEnrichedLagrange,
    CrouzeixRaviart,
    Lagrange,
    DiscontinuousLagrange,
    Serendipity,
    getnbasefunctions,

# Quadrature
    QuadratureRule,
    getweights,
    getpoints,

# FEValues
    CellValues,
    CellScalarValues,
    CellVectorValues,
    FaceValues,
    FaceScalarValues,
    FaceVectorValues,
    reinit!,
    shape_value,
    shape_gradient,
    shape_symmetric_gradient,
    shape_divergence,
    shape_curl,
    function_value,
    function_gradient,
    function_symmetric_gradient,
    function_divergence,
    function_curl,
    spatial_coordinate,
    getnormal,
    getdetJdV,
    getnquadpoints,

# Grid
    Grid,
    Node,
    Cell,
    Line,
    Line2D,
    Line3D,
    QuadraticLine,
    Triangle,
    QuadraticTriangle,
    Quadrilateral,
    Quadrilateral3D,
    QuadraticQuadrilateral,
    Tetrahedron,
    QuadraticTetrahedron,
    Hexahedron,
    #QuadraticHexahedron,
    CellIndex,
    FaceIndex,
    EdgeIndex,
    VertexIndex,
    CoverTopology,
    ExclusiveTopology,
    getneighborhood,
    faceskeleton,
    getcells,
    getgrid,
    getlocalgrid,
    getncells,
    getnodes,
    getnnodes,
    getcelltype,
    getcellset,
    getnodeset,
    getfaceset,
    getedgeset,
    getvertexset,
    getcoordinates,
    getcoordinates!,
    getcellsets,
    getnodesets,
    getfacesets,
    getedgesets,
    getvertexsets,
    getdim,
    onboundary,
    nfaces,
    addnodeset!,
    addfaceset!,
    addedgeset!,
    addvertexset!,
    addcellset!,
    transform!,
    generate_grid,
    compute_vertex_values,
    is_shared_vertex,
    get_shared_vertex,
    get_shared_vertices,
    is_shared_face,
    get_shared_face,
    get_shared_faces,
    is_shared_edge,
    get_shared_edge,
    get_shared_edges,

# Grid coloring
    create_coloring,
    ColoringAlgorithm,
    vtk_cell_data_colors,

# Dofs
    DofHandler,
    close!,
    ndofs,
    ndofs_per_cell,
    celldofs!,
    celldofs,
    cellcoords!,
    create_sparsity_pattern,
    create_symmetric_sparsity_pattern,
    dof_range,
    renumber!,
    DofOrder,
    MixedDofHandler,
    FieldHandler,
    Field,
    reshape_to_nodes,
    num_fields,
    field_offset,
    getfieldnames,
    getfielddim,
    dof_range,
    #entity_dofs,
    apply_analytical!,

# Constraints
    ConstraintHandler,
    Dirichlet,
    PeriodicDirichlet,
    collect_periodic_faces,
    collect_periodic_faces!,
    PeriodicFacePair,
    AffineConstraint,
    update!,
    apply!,
    apply_rhs!,
    get_rhs_data,
    apply_zero!,
    apply_local!,
    apply_assemble!,
    add!,
    free_dofs,
    ApplyStrategy,

# iterators
    CellCache,
    CellIterator,
    UpdateFlags,
    cellid,

# assembly
    start_assemble,
    assemble!,
    end_assemble,

# VTK export
    vtk_grid,
    vtk_point_data,
    vtk_cell_data,
    vtk_nodeset,
    vtk_cellset,
    vtk_save,
    vtk_shared_vertices,
    vtk_shared_faces,
    vtk_shared_edges,
    vtk_partitioning,

# L2 Projection
    project,
    L2Projector,

# Point Evaluation
    PointEvalHandler,
    get_point_values,
    PointIterator,
    PointLocation,
    PointScalarValues,
    PointVectorValues
