name: Test
on:
  pull_request:
  push:
    branches: ['master']
    tags: ['*']
jobs:
  test:
    name: Julia ${{ matrix.julia-version }} - ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 40
    continue-on-error: ${{ matrix.julia-version == 'nightly' }}
    strategy:
      matrix:
        julia-version: ['1.10', '1', 'nightly']
        os: ['ubuntu-latest']
        include:
          - os: windows-latest
            julia-version: '1'
          - os: macOS-latest
            julia-version: '1'
    steps:
      - uses: actions/checkout@v4
      - uses: julia-actions/setup-julia@v2
        with:
          version: ${{ matrix.julia-version }}
      - uses: julia-actions/cache@v2
      - uses: julia-actions/julia-buildpkg@v1
      - uses: julia-actions/julia-runtest@v1
      - name: JET tests
        shell: julia --color=yes --project=@jet {0}
        run: |
          using Pkg
          Pkg.add("JET")
          Pkg.develop(path = pwd())
          include(joinpath(pwd(), "test/jet.jl"))
        if: ${{ matrix.os == 'ubuntu-latest' && matrix.julia-version != 'nightly' }}
      - uses: julia-actions/julia-processcoverage@v1
        with:
          directories: 'src,ext'
      - uses: codecov/codecov-action@v5
        with:
          files: lcov.info
          plugins: noop
          disable_search: true
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
